Error: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2212' in position 204: ordinal not in range(128)
Fix:
Encoding error for a minus sign caused the bot to crash. I have applied a temporary fix.